"""Validate icons against Mintlify's supported icon sets.

Mintlify supports FontAwesome (free + pro) and Lucide icons. This module
validates icon names and strips unsupported ones so they don't render as
missing in the output.

Sources:
  FontAwesome 6.7.2 — https://api.fontawesome.com (GraphQL: release icons)
  Lucide — https://lucide.dev/api/tags
"""

from typing import Optional


VALID_ICONS: frozenset[str] = frozenset({
    "0", "00", "1", "2", "3", "360-degrees", "4", "42-group", "5", "500px", "6", "7", "8", "9", "a",
    "a-arrow-down", "a-arrow-up", "a-large-small", "abacus", "accent-grave", "accessibility",
    "accessible-icon", "accusoft", "acorn", "activity", "address-book", "address-card", "adn",
    "adversal", "affiliatetheme", "air-conditioner", "air-vent", "airbnb", "airplay", "alarm-clock",
    "alarm-clock-check", "alarm-clock-minus", "alarm-clock-off", "alarm-clock-plus",
    "alarm-exclamation", "alarm-plus", "alarm-smoke", "alarm-snooze", "album", "album-circle-plus",
    "album-circle-user", "album-collection", "album-collection-circle-plus",
    "album-collection-circle-user", "algolia", "alicorn", "alien", "alien-8bit", "align-center",
    "align-center-horizontal", "align-center-vertical", "align-end-horizontal",
    "align-end-vertical", "align-horizontal-distribute-center", "align-horizontal-distribute-end",
    "align-horizontal-distribute-start", "align-horizontal-justify-center",
    "align-horizontal-justify-end", "align-horizontal-justify-start",
    "align-horizontal-space-around", "align-horizontal-space-between", "align-justify",
    "align-left", "align-right", "align-slash", "align-start-horizontal", "align-start-vertical",
    "align-vertical-distribute-center", "align-vertical-distribute-end",
    "align-vertical-distribute-start", "align-vertical-justify-center",
    "align-vertical-justify-end", "align-vertical-justify-start", "align-vertical-space-around",
    "align-vertical-space-between", "alipay", "alt", "amazon", "amazon-pay", "ambulance", "amilia",
    "amp-guitar", "ampersand", "ampersands", "amphora", "anchor", "anchor-circle-check",
    "anchor-circle-exclamation", "anchor-circle-xmark", "anchor-lock", "android", "angel",
    "angellist", "angle", "angle-90", "angle-down", "angle-left", "angle-right", "angle-up",
    "angles-down", "angles-left", "angles-right", "angles-up", "angles-up-down", "angry",
    "angrycreative", "angular", "ankh", "annoyed", "ant", "antenna", "anvil", "apartment",
    "aperture", "apostrophe", "app-store", "app-store-ios", "app-window", "app-window-mac", "apper",
    "apple", "apple-core", "apple-pay", "apple-whole", "archive", "archive-restore", "archive-x",
    "archway", "armchair", "arrow-big-down", "arrow-big-down-dash", "arrow-big-left",
    "arrow-big-left-dash", "arrow-big-right", "arrow-big-right-dash", "arrow-big-up",
    "arrow-big-up-dash", "arrow-down", "arrow-down-0-1", "arrow-down-1-0", "arrow-down-1-9",
    "arrow-down-9-1", "arrow-down-a-z", "arrow-down-arrow-up", "arrow-down-big-small",
    "arrow-down-from-arc", "arrow-down-from-bracket", "arrow-down-from-dotted-line",
    "arrow-down-from-line", "arrow-down-left", "arrow-down-left-and-arrow-up-right-to-center",
    "arrow-down-long", "arrow-down-narrow-wide", "arrow-down-right", "arrow-down-short-wide",
    "arrow-down-small-big", "arrow-down-square-triangle", "arrow-down-to-arc",
    "arrow-down-to-bracket", "arrow-down-to-dot", "arrow-down-to-dotted-line", "arrow-down-to-line",
    "arrow-down-to-square", "arrow-down-triangle-square", "arrow-down-up",
    "arrow-down-up-across-line", "arrow-down-up-lock", "arrow-down-wide-narrow",
    "arrow-down-wide-short", "arrow-down-z-a", "arrow-left", "arrow-left-from-arc",
    "arrow-left-from-bracket", "arrow-left-from-line", "arrow-left-long", "arrow-left-long-to-line",
    "arrow-left-right", "arrow-left-to-arc", "arrow-left-to-bracket", "arrow-left-to-line",
    "arrow-pointer", "arrow-progress", "arrow-right", "arrow-right-arrow-left",
    "arrow-right-from-arc", "arrow-right-from-bracket", "arrow-right-from-line", "arrow-right-left",
    "arrow-right-long", "arrow-right-long-to-line", "arrow-right-to-arc", "arrow-right-to-bracket",
    "arrow-right-to-city", "arrow-right-to-line", "arrow-rotate-left", "arrow-rotate-right",
    "arrow-trend-down", "arrow-trend-up", "arrow-turn-down", "arrow-turn-down-left",
    "arrow-turn-down-right", "arrow-turn-left", "arrow-turn-left-down", "arrow-turn-left-up",
    "arrow-turn-right", "arrow-turn-up", "arrow-up", "arrow-up-0-1", "arrow-up-1-0", "arrow-up-1-9",
    "arrow-up-9-1", "arrow-up-a-z", "arrow-up-arrow-down", "arrow-up-big-small", "arrow-up-down",
    "arrow-up-from-arc", "arrow-up-from-bracket", "arrow-up-from-dot", "arrow-up-from-dotted-line",
    "arrow-up-from-ground-water", "arrow-up-from-line", "arrow-up-from-square",
    "arrow-up-from-water-pump", "arrow-up-left", "arrow-up-left-from-circle", "arrow-up-long",
    "arrow-up-narrow-wide", "arrow-up-right", "arrow-up-right-and-arrow-down-left-from-center",
    "arrow-up-right-dots", "arrow-up-right-from-square", "arrow-up-short-wide",
    "arrow-up-small-big", "arrow-up-square-triangle", "arrow-up-to-arc", "arrow-up-to-bracket",
    "arrow-up-to-dotted-line", "arrow-up-to-line", "arrow-up-triangle-square",
    "arrow-up-wide-narrow", "arrow-up-wide-short", "arrow-up-z-a", "arrows-cross",
    "arrows-down-to-line", "arrows-down-to-people", "arrows-from-dotted-line", "arrows-from-line",
    "arrows-left-right", "arrows-left-right-to-line", "arrows-maximize", "arrows-minimize",
    "arrows-repeat", "arrows-repeat-1", "arrows-retweet", "arrows-rotate", "arrows-rotate-reverse",
    "arrows-spin", "arrows-split-up-and-left", "arrows-to-circle", "arrows-to-dot",
    "arrows-to-dotted-line", "arrows-to-eye", "arrows-to-line", "arrows-turn-right",
    "arrows-turn-to-dots", "arrows-up-down", "arrows-up-down-left-right", "arrows-up-from-line",
    "arrows-up-to-line", "artstation", "asterisk", "asymmetrik", "at", "at-sign", "atlassian",
    "atom", "atom-simple", "audible", "audio-description", "audio-description-slash", "audio-lines",
    "audio-waveform", "austral-sign", "autoprefixer", "avianex", "aviato", "avocado", "award",
    "award-simple", "aws", "axe", "axe-battle", "axis-3d", "b", "baby", "baby-carriage", "backpack",
    "backward", "backward-fast", "backward-step", "bacon", "bacteria", "bacterium", "badge",
    "badge-alert", "badge-cent", "badge-check", "badge-dollar", "badge-dollar-sign", "badge-euro",
    "badge-indian-rupee", "badge-info", "badge-japanese-yen", "badge-minus", "badge-percent",
    "badge-plus", "badge-pound-sterling", "badge-question-mark", "badge-russian-ruble",
    "badge-sheriff", "badge-swiss-franc", "badge-turkish-lira", "badge-x", "badger-honey",
    "badminton", "bag-seedling", "bag-shopping", "bag-shopping-minus", "bag-shopping-plus", "bagel",
    "baggage-claim", "bags-shopping", "baguette", "bahai", "baht-sign", "ball-pile", "balloon",
    "balloons", "ballot", "ballot-check", "ban", "ban-bug", "ban-parking", "ban-smoking", "banana",
    "bandage", "bandcamp", "bangladeshi-taka-sign", "banjo", "banknote", "banknote-arrow-down",
    "banknote-arrow-up", "banknote-x", "barcode", "barcode-read", "barcode-scan", "barrel", "bars",
    "bars-filter", "bars-progress", "bars-sort", "bars-staggered", "baseball", "baseball-bat-ball",
    "baseline", "basket-shopping", "basket-shopping-minus", "basket-shopping-plus",
    "basket-shopping-simple", "basketball", "basketball-hoop", "bat", "bath", "battery",
    "battery-bolt", "battery-charging", "battery-empty", "battery-exclamation", "battery-full",
    "battery-half", "battery-low", "battery-medium", "battery-plus", "battery-quarter",
    "battery-slash", "battery-three-quarters", "battery-warning", "battle-net", "beaker", "bean",
    "bean-off", "bed", "bed-bunk", "bed-double", "bed-empty", "bed-front", "bed-pulse",
    "bed-single", "bee", "beef", "beer", "beer-mug", "beer-mug-empty", "beer-off", "behance",
    "bell", "bell-concierge", "bell-dot", "bell-electric", "bell-exclamation", "bell-minus",
    "bell-off", "bell-on", "bell-plus", "bell-ring", "bell-school", "bell-school-slash",
    "bell-slash", "bells", "bench-tree", "between-horizontal-end", "between-horizontal-start",
    "between-vertical-end", "between-vertical-start", "bezier-curve", "biceps-flexed", "bicycle",
    "bike", "bilibili", "billboard", "bimobject", "bin-bottles", "bin-bottles-recycle",
    "bin-recycle", "binary", "binary-circle-check", "binary-lock", "binary-slash", "binoculars",
    "biohazard", "bird", "birdhouse", "bitbucket", "bitcoin", "bitcoin-sign", "bity", "black-tie",
    "blackberry", "blanket", "blanket-fire", "blend", "blender", "blender-phone", "blinds",
    "blinds-open", "blinds-raised", "block", "block-brick", "block-brick-fire", "block-question",
    "block-quote", "blocks", "blog", "blogger", "blogger-b", "blueberries", "bluesky", "bluetooth",
    "bluetooth-b", "bluetooth-connected", "bluetooth-off", "bluetooth-searching", "bold", "bolt",
    "bolt-auto", "bolt-lightning", "bolt-slash", "bomb", "bone", "bone-break", "bong", "book",
    "book-a", "book-alert", "book-arrow-right", "book-arrow-up", "book-atlas", "book-audio",
    "book-bible", "book-blank", "book-bookmark", "book-check", "book-circle-arrow-right",
    "book-circle-arrow-up", "book-copy", "book-dashed", "book-down", "book-font", "book-headphones",
    "book-heart", "book-image", "book-journal-whills", "book-key", "book-lock", "book-marked",
    "book-medical", "book-minus", "book-open", "book-open-check", "book-open-cover",
    "book-open-reader", "book-open-text", "book-plus", "book-quran", "book-search", "book-section",
    "book-skull", "book-sparkles", "book-tanakh", "book-text", "book-type", "book-up", "book-up-2",
    "book-user", "book-x", "bookmark", "bookmark-check", "bookmark-minus", "bookmark-plus",
    "bookmark-slash", "bookmark-x", "books", "books-medical", "boom-box", "boombox", "boot",
    "boot-heeled", "booth-curtain", "bootstrap", "border-all", "border-bottom",
    "border-bottom-right", "border-center-h", "border-center-v", "border-inner", "border-left",
    "border-none", "border-outer", "border-right", "border-top", "border-top-left", "bore-hole",
    "bot", "bot-message-square", "bot-off", "bots", "bottle-baby", "bottle-droplet", "bottle-water",
    "bottle-wine", "bow-arrow", "bowl-chopsticks", "bowl-chopsticks-noodles", "bowl-food",
    "bowl-hot", "bowl-rice", "bowl-scoop", "bowl-scoops", "bowl-soft-serve", "bowl-spoon",
    "bowling-ball", "bowling-ball-pin", "bowling-pins", "box", "box-archive", "box-ballot",
    "box-check", "box-circle-check", "box-dollar", "box-heart", "box-open", "box-open-full",
    "box-taped", "box-tissue", "boxes", "boxes-packing", "boxes-stacked", "boxing-glove", "braces",
    "bracket-curly", "bracket-curly-right", "bracket-round", "bracket-round-right",
    "bracket-square", "bracket-square-right", "brackets", "brackets-curly", "brackets-round",
    "brackets-square", "braille", "brain", "brain-arrow-curved-right", "brain-circuit", "brain-cog",
    "brake-warning", "brave", "brave-reverse", "brazilian-real-sign", "bread-loaf", "bread-slice",
    "bread-slice-butter", "brick-wall", "brick-wall-fire", "brick-wall-shield", "bridge",
    "bridge-circle-check", "bridge-circle-exclamation", "bridge-circle-xmark", "bridge-lock",
    "bridge-suspension", "bridge-water", "briefcase", "briefcase-arrow-right", "briefcase-blank",
    "briefcase-business", "briefcase-conveyor-belt", "briefcase-medical", "brightness",
    "brightness-low", "bring-forward", "bring-front", "bring-to-front", "broccoli", "broom",
    "broom-ball", "broom-wide", "browser", "browsers", "brush", "brush-cleaning", "btc", "bubbles",
    "bucket", "buffer", "bug", "bug-off", "bug-play", "bug-slash", "bugs", "building", "building-2",
    "building-circle-arrow-right", "building-circle-check", "building-circle-exclamation",
    "building-circle-xmark", "building-columns", "building-flag", "building-lock",
    "building-magnifying-glass", "building-memo", "building-ngo", "building-shield", "building-un",
    "building-user", "building-wheat", "buildings", "bulldozer", "bullhorn", "bullseye",
    "bullseye-arrow", "bullseye-pointer", "buoy", "buoy-mooring", "burger", "burger-cheese",
    "burger-fries", "burger-glass", "burger-lettuce", "burger-soda", "buromobelexperte", "burrito",
    "burst", "bus", "bus-front", "bus-school", "bus-simple", "business-time", "butter",
    "buy-n-large", "buysellads", "c", "cabin", "cabinet-filing", "cable", "cable-car", "cactus",
    "caduceus", "cake", "cake-candles", "cake-slice", "calculator", "calculator-simple", "calendar",
    "calendar-1", "calendar-arrow-down", "calendar-arrow-up", "calendar-check", "calendar-check-2",
    "calendar-circle-exclamation", "calendar-circle-minus", "calendar-circle-plus",
    "calendar-circle-user", "calendar-clock", "calendar-cog", "calendar-day", "calendar-days",
    "calendar-exclamation", "calendar-fold", "calendar-heart", "calendar-image", "calendar-lines",
    "calendar-lines-pen", "calendar-minus", "calendar-minus-2", "calendar-off", "calendar-pen",
    "calendar-plus", "calendar-plus-2", "calendar-range", "calendar-search", "calendar-star",
    "calendar-sync", "calendar-users", "calendar-week", "calendar-x", "calendar-x-2",
    "calendar-xmark", "calendars", "camcorder", "camera", "camera-cctv", "camera-movie",
    "camera-off", "camera-polaroid", "camera-retro", "camera-rotate", "camera-security",
    "camera-slash", "camera-viewfinder", "camera-web", "camera-web-slash", "campfire", "campground",
    "can-food", "canadian-maple-leaf", "candle-holder", "candy", "candy-bar", "candy-cane",
    "candy-corn", "candy-off", "cannabis", "cannabis-off", "cannon", "capsules", "captions",
    "captions-off", "car", "car-battery", "car-bolt", "car-building", "car-bump", "car-burst",
    "car-bus", "car-circle-bolt", "car-front", "car-garage", "car-mirrors", "car-on", "car-rear",
    "car-side", "car-side-bolt", "car-taxi-front", "car-tilt", "car-tunnel", "car-wash",
    "car-wrench", "caravan", "caravan-simple", "card-club", "card-diamond", "card-heart",
    "card-sim", "card-spade", "cards", "cards-blank", "caret-down", "caret-left", "caret-right",
    "caret-up", "carpool", "carrot", "cars", "cart-arrow-down", "cart-arrow-up",
    "cart-circle-arrow-down", "cart-circle-arrow-up", "cart-circle-check",
    "cart-circle-exclamation", "cart-circle-plus", "cart-circle-xmark", "cart-flatbed",
    "cart-flatbed-boxes", "cart-flatbed-empty", "cart-flatbed-suitcase", "cart-minus", "cart-plus",
    "cart-shopping", "cart-shopping-fast", "cart-xmark", "case-lower", "case-sensitive",
    "case-upper", "cash-register", "cassette-betamax", "cassette-tape", "cassette-vhs", "cast",
    "castle", "cat", "cat-space", "cauldron", "cc-amazon-pay", "cc-amex", "cc-apple-pay",
    "cc-diners-club", "cc-discover", "cc-jcb", "cc-mastercard", "cc-paypal", "cc-stripe", "cc-visa",
    "cctv", "cedi-sign", "cent-sign", "centercode", "centos", "certificate", "chair",
    "chair-office", "chalkboard", "chalkboard-user", "champagne-glass", "champagne-glasses",
    "charging-station", "chart-area", "chart-bar", "chart-bar-big", "chart-bar-decreasing",
    "chart-bar-increasing", "chart-bar-stacked", "chart-bullet", "chart-candlestick",
    "chart-column", "chart-column-big", "chart-column-decreasing", "chart-column-increasing",
    "chart-column-stacked", "chart-diagram", "chart-fft", "chart-gantt", "chart-kanban",
    "chart-line", "chart-line-down", "chart-line-up", "chart-line-up-down", "chart-mixed",
    "chart-mixed-up-circle-currency", "chart-mixed-up-circle-dollar", "chart-network",
    "chart-no-axes-column", "chart-no-axes-column-decreasing", "chart-no-axes-column-increasing",
    "chart-no-axes-combined", "chart-no-axes-gantt", "chart-pie", "chart-pie-simple",
    "chart-pie-simple-circle-currency", "chart-pie-simple-circle-dollar", "chart-pyramid",
    "chart-radar", "chart-scatter", "chart-scatter-3d", "chart-scatter-bubble", "chart-simple",
    "chart-simple-horizontal", "chart-sine", "chart-spline", "chart-tree-map", "chart-user",
    "chart-waterfall", "check", "check-check", "check-double", "check-line", "check-to-slot",
    "cheese", "cheese-swiss", "chef-hat", "cherries", "cherry", "chess", "chess-bishop",
    "chess-bishop-piece", "chess-board", "chess-clock", "chess-clock-flip", "chess-king",
    "chess-king-piece", "chess-knight", "chess-knight-piece", "chess-pawn", "chess-pawn-piece",
    "chess-queen", "chess-queen-piece", "chess-rook", "chess-rook-piece", "chestnut",
    "chevron-down", "chevron-first", "chevron-last", "chevron-left", "chevron-right", "chevron-up",
    "chevrons-down", "chevrons-down-up", "chevrons-left", "chevrons-left-right",
    "chevrons-left-right-ellipsis", "chevrons-right", "chevrons-right-left", "chevrons-up",
    "chevrons-up-down", "chf-sign", "child", "child-combatant", "child-dress", "child-reaching",
    "children", "chimney", "chopsticks", "chrome", "chromecast", "chromium", "church", "cigarette",
    "cigarette-off", "circle", "circle-0", "circle-1", "circle-2", "circle-3", "circle-4",
    "circle-5", "circle-6", "circle-7", "circle-8", "circle-9", "circle-a", "circle-alert",
    "circle-ampersand", "circle-arrow-down", "circle-arrow-down-left", "circle-arrow-down-right",
    "circle-arrow-left", "circle-arrow-out-down-left", "circle-arrow-out-down-right",
    "circle-arrow-out-up-left", "circle-arrow-out-up-right", "circle-arrow-right",
    "circle-arrow-up", "circle-arrow-up-left", "circle-arrow-up-right", "circle-b", "circle-bolt",
    "circle-book-open", "circle-bookmark", "circle-c", "circle-calendar", "circle-camera",
    "circle-caret-down", "circle-caret-left", "circle-caret-right", "circle-caret-up",
    "circle-check", "circle-check-big", "circle-chevron-down", "circle-chevron-left",
    "circle-chevron-right", "circle-chevron-up", "circle-d", "circle-dashed", "circle-divide",
    "circle-dollar", "circle-dollar-sign", "circle-dollar-to-slot", "circle-dot",
    "circle-dot-dashed", "circle-down", "circle-down-left", "circle-down-right", "circle-e",
    "circle-ellipsis", "circle-ellipsis-vertical", "circle-envelope", "circle-equal", "circle-euro",
    "circle-exclamation", "circle-exclamation-check", "circle-f", "circle-fading-arrow-up",
    "circle-fading-plus", "circle-g", "circle-gauge", "circle-gf", "circle-h", "circle-half",
    "circle-half-stroke", "circle-heart", "circle-i", "circle-info", "circle-j", "circle-k",
    "circle-l", "circle-left", "circle-location-arrow", "circle-m", "circle-microphone",
    "circle-microphone-lines", "circle-minus", "circle-n", "circle-nodes", "circle-notch",
    "circle-o", "circle-off", "circle-p", "circle-parking", "circle-parking-off", "circle-pause",
    "circle-percent", "circle-phone", "circle-phone-flip", "circle-phone-hangup", "circle-pile",
    "circle-play", "circle-plus", "circle-pound-sterling", "circle-power", "circle-q",
    "circle-quarter", "circle-quarter-stroke", "circle-quarters", "circle-question",
    "circle-question-mark", "circle-r", "circle-radiation", "circle-right", "circle-s",
    "circle-slash", "circle-slash-2", "circle-small", "circle-sort", "circle-sort-down",
    "circle-sort-up", "circle-star", "circle-sterling", "circle-stop", "circle-t",
    "circle-three-quarters", "circle-three-quarters-stroke", "circle-trash", "circle-u",
    "circle-up", "circle-up-left", "circle-up-right", "circle-user", "circle-user-round",
    "circle-v", "circle-video", "circle-w", "circle-waveform-lines", "circle-wifi",
    "circle-wifi-circle-wifi", "circle-x", "circle-xmark", "circle-y", "circle-yen", "circle-z",
    "circles-overlap", "circles-overlap-3", "circuit-board", "citrus", "citrus-slice", "city",
    "clapperboard", "clapperboard-play", "clarinet", "claw-marks", "clipboard", "clipboard-check",
    "clipboard-clock", "clipboard-copy", "clipboard-list", "clipboard-list-check",
    "clipboard-medical", "clipboard-minus", "clipboard-paste", "clipboard-pen",
    "clipboard-pen-line", "clipboard-plus", "clipboard-prescription", "clipboard-question",
    "clipboard-type", "clipboard-user", "clipboard-x", "clock", "clock-1", "clock-10", "clock-11",
    "clock-12", "clock-2", "clock-3", "clock-4", "clock-5", "clock-6", "clock-7", "clock-8",
    "clock-9", "clock-alert", "clock-arrow-down", "clock-arrow-up", "clock-check", "clock-desk",
    "clock-eight", "clock-eight-thirty", "clock-eleven", "clock-eleven-thirty", "clock-fading",
    "clock-five", "clock-five-thirty", "clock-four-thirty", "clock-nine", "clock-nine-thirty",
    "clock-one", "clock-one-thirty", "clock-plus", "clock-rotate-left", "clock-seven",
    "clock-seven-thirty", "clock-six", "clock-six-thirty", "clock-ten", "clock-ten-thirty",
    "clock-three", "clock-three-thirty", "clock-twelve", "clock-twelve-thirty", "clock-two",
    "clock-two-thirty", "clone", "closed-caption", "closed-captioning", "closed-captioning-slash",
    "clothes-hanger", "cloud", "cloud-alert", "cloud-arrow-down", "cloud-arrow-up", "cloud-backup",
    "cloud-binary", "cloud-bolt", "cloud-bolt-moon", "cloud-bolt-sun", "cloud-check", "cloud-cog",
    "cloud-download", "cloud-drizzle", "cloud-exclamation", "cloud-fog", "cloud-hail",
    "cloud-hail-mixed", "cloud-lightning", "cloud-meatball", "cloud-minus", "cloud-moon",
    "cloud-moon-rain", "cloud-music", "cloud-off", "cloud-plus", "cloud-question", "cloud-rain",
    "cloud-rain-wind", "cloud-rainbow", "cloud-showers", "cloud-showers-heavy",
    "cloud-showers-water", "cloud-slash", "cloud-sleet", "cloud-snow", "cloud-sun",
    "cloud-sun-rain", "cloud-sync", "cloud-upload", "cloud-word", "cloud-xmark", "cloudflare",
    "clouds", "clouds-moon", "clouds-sun", "cloudscale", "cloudsmith", "cloudversify", "cloudy",
    "clover", "club", "cmplid", "coconut", "code", "code-branch", "code-commit", "code-compare",
    "code-fork", "code-merge", "code-pull-request", "code-pull-request-closed",
    "code-pull-request-draft", "code-simple", "code-xml", "codepen", "codesandbox", "codiepie",
    "coffee", "coffee-bean", "coffee-beans", "coffee-pot", "coffin", "coffin-cross", "cog", "coin",
    "coin-blank", "coin-front", "coin-vertical", "coins", "colon", "colon-sign", "columns-2",
    "columns-3", "columns-3-cog", "columns-4", "combine", "comet", "comma", "command", "comment",
    "comment-arrow-down", "comment-arrow-up", "comment-arrow-up-right", "comment-captions",
    "comment-check", "comment-code", "comment-dollar", "comment-dots", "comment-exclamation",
    "comment-heart", "comment-image", "comment-lines", "comment-medical", "comment-middle",
    "comment-middle-top", "comment-minus", "comment-music", "comment-nodes", "comment-pen",
    "comment-plus", "comment-question", "comment-quote", "comment-slash", "comment-smile",
    "comment-sms", "comment-text", "comment-xmark", "comments", "comments-dollar",
    "comments-question", "comments-question-check", "compact-disc", "compass", "compass-drafting",
    "compass-slash", "component", "compress", "compress-wide", "computer", "computer-classic",
    "computer-mouse", "computer-mouse-scrollwheel", "computer-speaker", "concierge-bell", "cone",
    "confluence", "connectdevelop", "construction", "contact", "contact-round", "container",
    "container-storage", "contao", "contrast", "conveyor-belt", "conveyor-belt-arm",
    "conveyor-belt-boxes", "conveyor-belt-empty", "cookie", "cookie-bite", "cooking-pot", "copy",
    "copy-check", "copy-minus", "copy-plus", "copy-slash", "copy-x", "copyleft", "copyright",
    "corn", "corner", "corner-down-left", "corner-down-right", "corner-left-down", "corner-left-up",
    "corner-right-down", "corner-right-up", "corner-up-left", "corner-up-right", "cotton-bureau",
    "couch", "court-sport", "cow", "cowbell", "cowbell-circle-plus", "cpanel", "cpu", "crab",
    "crate-apple", "crate-empty", "creative-commons", "creative-commons-by", "creative-commons-nc",
    "creative-commons-nc-eu", "creative-commons-nc-jp", "creative-commons-nd",
    "creative-commons-pd", "creative-commons-pd-alt", "creative-commons-remix",
    "creative-commons-sa", "creative-commons-sampling", "creative-commons-sampling-plus",
    "creative-commons-share", "creative-commons-zero", "credit-card", "credit-card-blank",
    "credit-card-front", "cricket-bat-ball", "critical-role", "croissant", "crop", "crop-simple",
    "cross", "crosshair", "crosshairs", "crosshairs-simple", "crow", "crown", "crutch", "crutches",
    "cruzeiro-sign", "crystal-ball", "css", "css3", "css3-alt", "cube", "cubes", "cubes-stacked",
    "cuboid", "cucumber", "cup-soda", "cup-straw", "cup-straw-swoosh", "cup-togo", "cupcake",
    "curling-stone", "currency", "custard", "cuttlefish", "cylinder", "d", "d-and-d",
    "d-and-d-beyond", "dagger", "dailymotion", "dam", "dart-lang", "dash", "dashcube", "database",
    "database-backup", "database-search", "database-zap", "debian", "decimals-arrow-left",
    "decimals-arrow-right", "deer", "deer-rudolph", "deezer", "delete", "delete-left",
    "delete-right", "delicious", "democrat", "deploydog", "deskpro", "desktop",
    "desktop-arrow-down", "dessert", "dev", "deviantart", "dharmachakra", "dhl", "diagram-cells",
    "diagram-lean-canvas", "diagram-nested", "diagram-next", "diagram-predecessor",
    "diagram-previous", "diagram-project", "diagram-sankey", "diagram-subtask", "diagram-successor",
    "diagram-venn", "dial", "dial-high", "dial-low", "dial-max", "dial-med", "dial-med-low",
    "dial-min", "dial-off", "diameter", "diamond", "diamond-exclamation", "diamond-half",
    "diamond-half-stroke", "diamond-minus", "diamond-percent", "diamond-plus", "diamond-turn-right",
    "diamonds-4", "diaspora", "dice", "dice-1", "dice-2", "dice-3", "dice-4", "dice-5", "dice-6",
    "dice-d10", "dice-d12", "dice-d20", "dice-d4", "dice-d6", "dice-d8", "dice-five", "dice-four",
    "dice-one", "dice-six", "dice-three", "dice-two", "dices", "diff", "digg", "digital-ocean",
    "dinosaur", "diploma", "disc", "disc-2", "disc-3", "disc-album", "disc-drive", "discord",
    "discourse", "disease", "display", "display-arrow-down", "display-chart-up",
    "display-chart-up-circle-currency", "display-chart-up-circle-dollar", "display-code",
    "display-medical", "display-slash", "distribute-spacing-horizontal",
    "distribute-spacing-vertical", "ditto", "divide", "dna", "dna-off", "do-not-enter", "dochub",
    "dock", "docker", "dog", "dog-leashed", "dollar-sign", "dolly", "dolly-empty", "dolphin",
    "dong-sign", "donut", "door-closed", "door-closed-locked", "door-open", "dot", "dove", "down",
    "down-from-bracket", "down-from-dotted-line", "down-from-line", "down-left",
    "down-left-and-up-right-to-center", "down-long", "down-right", "down-to-bracket",
    "down-to-dotted-line", "down-to-line", "download", "draft2digital", "drafting-compass",
    "dragon", "drama", "draw-circle", "draw-polygon", "draw-square", "dreidel", "dribbble", "drill",
    "drone", "drone-front", "dropbox", "droplet", "droplet-degree", "droplet-off",
    "droplet-percent", "droplet-slash", "droplets", "drum", "drum-steelpan", "drumstick",
    "drumstick-bite", "drupal", "dryer", "dryer-heat", "duck", "dumbbell", "dumpster",
    "dumpster-fire", "dungeon", "dyalog", "e", "ear", "ear-deaf", "ear-listen", "ear-muffs",
    "ear-off", "earlybirds", "earth", "earth-africa", "earth-americas", "earth-asia",
    "earth-europe", "earth-lock", "earth-oceania", "ebay", "eclipse", "edge", "edge-legacy", "egg",
    "egg-fried", "egg-off", "eggplant", "eject", "elementor", "elephant", "elevator", "ellipsis",
    "ellipsis-stroke", "ellipsis-stroke-vertical", "ellipsis-vertical", "ello", "ember", "empire",
    "empty-set", "engine", "engine-warning", "envelope", "envelope-circle-check", "envelope-dot",
    "envelope-open", "envelope-open-dollar", "envelope-open-text", "envelopes", "envelopes-bulk",
    "envira", "equal", "equal-approximately", "equal-not", "equals", "eraser", "erlang",
    "escalator", "ethereum", "ethernet", "ethernet-port", "etsy", "euro", "euro-sign", "ev-charger",
    "evernote", "excavator", "exclamation", "expand", "expand-wide", "expeditedssl", "explosion",
    "external-link", "eye", "eye-closed", "eye-dropper", "eye-dropper-full", "eye-dropper-half",
    "eye-evil", "eye-low-vision", "eye-off", "eye-slash", "eyes", "f", "face-angry",
    "face-angry-horns", "face-anguished", "face-anxious-sweat", "face-astonished", "face-awesome",
    "face-beam-hand-over-mouth", "face-clouds", "face-confounded", "face-confused",
    "face-cowboy-hat", "face-diagonal-mouth", "face-disappointed", "face-disguise", "face-dizzy",
    "face-dotted", "face-downcast-sweat", "face-drooling", "face-exhaling", "face-explode",
    "face-expressionless", "face-eyes-xmarks", "face-fearful", "face-flushed", "face-frown",
    "face-frown-open", "face-frown-slight", "face-glasses", "face-grimace", "face-grin",
    "face-grin-beam", "face-grin-beam-sweat", "face-grin-hearts", "face-grin-squint",
    "face-grin-squint-tears", "face-grin-stars", "face-grin-tears", "face-grin-tongue",
    "face-grin-tongue-squint", "face-grin-tongue-wink", "face-grin-wide", "face-grin-wink",
    "face-hand-over-mouth", "face-hand-peeking", "face-hand-yawn", "face-head-bandage",
    "face-holding-back-tears", "face-hushed", "face-icicles", "face-kiss", "face-kiss-beam",
    "face-kiss-closed-eyes", "face-kiss-wink-heart", "face-laugh", "face-laugh-beam",
    "face-laugh-squint", "face-laugh-wink", "face-lying", "face-mask", "face-meh", "face-meh-blank",
    "face-melting", "face-monocle", "face-nauseated", "face-nose-steam", "face-party",
    "face-pensive", "face-persevering", "face-pleading", "face-pouting", "face-raised-eyebrow",
    "face-relieved", "face-rolling-eyes", "face-sad-cry", "face-sad-sweat", "face-sad-tear",
    "face-saluting", "face-scream", "face-shush", "face-sleeping", "face-sleepy", "face-smile",
    "face-smile-beam", "face-smile-halo", "face-smile-hearts", "face-smile-horns",
    "face-smile-plus", "face-smile-relaxed", "face-smile-tear", "face-smile-tongue",
    "face-smile-upside-down", "face-smile-wink", "face-smiling-hands", "face-smirking",
    "face-spiral-eyes", "face-sunglasses", "face-surprise", "face-swear", "face-thermometer",
    "face-thinking", "face-tired", "face-tissue", "face-tongue-money", "face-tongue-sweat",
    "face-unamused", "face-viewfinder", "face-vomit", "face-weary", "face-woozy", "face-worried",
    "face-zany", "face-zipper", "facebook", "facebook-f", "facebook-messenger", "factory",
    "falafel", "family", "family-dress", "family-pants", "fan", "fan-table", "fantasy-flight-games",
    "farm", "fast-forward", "faucet", "faucet-drip", "fax", "feather", "feather-pointed", "fedex",
    "fedora", "fence", "ferris-wheel", "ferry", "field-hockey-stick-ball", "figma", "file",
    "file-archive", "file-arrow-down", "file-arrow-up", "file-audio", "file-axis-3d", "file-badge",
    "file-binary", "file-box", "file-braces", "file-braces-corner", "file-cad", "file-certificate",
    "file-chart-column", "file-chart-column-increasing", "file-chart-line", "file-chart-pie",
    "file-check", "file-check-corner", "file-circle-check", "file-circle-exclamation",
    "file-circle-info", "file-circle-minus", "file-circle-plus", "file-circle-question",
    "file-circle-xmark", "file-clock", "file-code", "file-code-corner", "file-cog", "file-contract",
    "file-csv", "file-dashed-line", "file-diff", "file-digit", "file-doc", "file-down", "file-eps",
    "file-excel", "file-exclamation", "file-exclamation-point", "file-export", "file-fragment",
    "file-gif", "file-half-dashed", "file-headphone", "file-heart", "file-image", "file-import",
    "file-input", "file-invoice", "file-invoice-dollar", "file-jpg", "file-key", "file-lines",
    "file-lock", "file-magnifying-glass", "file-medical", "file-minus", "file-minus-corner",
    "file-mov", "file-mp3", "file-mp4", "file-music", "file-output", "file-pdf", "file-pen",
    "file-pen-line", "file-play", "file-plus", "file-plus-corner", "file-plus-minus", "file-png",
    "file-powerpoint", "file-ppt", "file-prescription", "file-question-mark", "file-scan",
    "file-search", "file-search-corner", "file-shield", "file-signal", "file-signature",
    "file-slash", "file-sliders", "file-spreadsheet", "file-stack", "file-svg", "file-symlink",
    "file-terminal", "file-text", "file-type", "file-type-corner", "file-up", "file-user",
    "file-vector", "file-video", "file-video-camera", "file-volume", "file-waveform", "file-word",
    "file-x", "file-x-corner", "file-xls", "file-xmark", "file-xml", "file-zip", "file-zipper",
    "files", "files-medical", "files-pinwheel", "fill", "fill-drip", "film", "film-canister",
    "film-simple", "film-slash", "films", "filter", "filter-circle-dollar", "filter-circle-xmark",
    "filter-list", "filter-slash", "filters", "fingerprint", "fingerprint-pattern", "fire",
    "fire-burner", "fire-extinguisher", "fire-flame", "fire-flame-curved", "fire-flame-simple",
    "fire-hydrant", "fire-smoke", "firefox", "firefox-browser", "fireplace", "first-order",
    "first-order-alt", "firstdraft", "fish", "fish-bones", "fish-cooked", "fish-fins", "fish-off",
    "fish-symbol", "fishing-hook", "fishing-rod", "flag", "flag-checkered", "flag-off",
    "flag-pennant", "flag-swallowtail", "flag-triangle-left", "flag-triangle-right", "flag-usa",
    "flame", "flame-kindling", "flashlight", "flashlight-off", "flask", "flask-conical",
    "flask-conical-off", "flask-gear", "flask-round", "flask-round-poison", "flask-round-potion",
    "flask-vial", "flatbread", "flatbread-stuffed", "flickr", "flip-horizontal-2",
    "flip-vertical-2", "flipboard", "floppy-disk", "floppy-disk-circle-arrow-right",
    "floppy-disk-circle-xmark", "floppy-disk-pen", "floppy-disks", "florin-sign", "flower",
    "flower-2", "flower-daffodil", "flower-tulip", "flute", "flutter", "flux-capacitor", "fly",
    "flying-disc", "focus", "fold-horizontal", "fold-vertical", "folder", "folder-archive",
    "folder-arrow-down", "folder-arrow-up", "folder-bookmark", "folder-check", "folder-clock",
    "folder-closed", "folder-code", "folder-cog", "folder-dot", "folder-down", "folder-gear",
    "folder-git", "folder-git-2", "folder-grid", "folder-heart", "folder-image", "folder-input",
    "folder-kanban", "folder-key", "folder-lock", "folder-magnifying-glass", "folder-medical",
    "folder-minus", "folder-music", "folder-open", "folder-open-dot", "folder-output", "folder-pen",
    "folder-plus", "folder-root", "folder-search", "folder-search-2", "folder-symlink",
    "folder-sync", "folder-tree", "folder-up", "folder-user", "folder-x", "folder-xmark", "folders",
    "fondue-pot", "font", "font-awesome", "font-case", "fonticons", "fonticons-fi", "football",
    "football-helmet", "footprints", "fork", "fork-knife", "forklift", "form", "fort",
    "fort-awesome", "fort-awesome-alt", "forumbee", "forward", "forward-fast", "forward-step",
    "foursquare", "frame", "framer", "franc-sign", "free-code-camp", "freebsd", "french-fries",
    "frog", "frown", "fuel", "fulcrum", "fullscreen", "function", "funnel", "funnel-plus",
    "funnel-x", "futbol", "g", "galactic-republic", "galactic-senate", "galaxy",
    "gallery-horizontal", "gallery-horizontal-end", "gallery-thumbnails", "gallery-vertical",
    "gallery-vertical-end", "game-board", "game-board-simple", "game-console-handheld",
    "game-console-handheld-crank", "gamepad", "gamepad-2", "gamepad-directional", "gamepad-modern",
    "garage", "garage-car", "garage-open", "garlic", "gas-pump", "gas-pump-slash", "gauge",
    "gauge-circle-bolt", "gauge-circle-minus", "gauge-circle-plus", "gauge-high", "gauge-low",
    "gauge-max", "gauge-min", "gauge-simple", "gauge-simple-high", "gauge-simple-low",
    "gauge-simple-max", "gauge-simple-min", "gavel", "gear", "gear-code", "gear-complex",
    "gear-complex-code", "gears", "gem", "genderless", "georgian-lari", "get-pocket", "gg",
    "gg-circle", "ghost", "gif", "gift", "gift-card", "gifts", "gingerbread-man", "git", "git-alt",
    "git-branch", "git-branch-minus", "git-branch-plus", "git-commit-horizontal",
    "git-commit-vertical", "git-compare", "git-compare-arrows", "git-fork", "git-graph",
    "git-merge", "git-merge-conflict", "git-pull-request", "git-pull-request-arrow",
    "git-pull-request-closed", "git-pull-request-create", "git-pull-request-create-arrow",
    "git-pull-request-draft", "github", "github-alt", "gitkraken", "gitlab", "gitter", "glass",
    "glass-citrus", "glass-empty", "glass-half", "glass-water", "glass-water-droplet", "glasses",
    "glasses-round", "glide", "glide-g", "globe", "globe-lock", "globe-off", "globe-pointer",
    "globe-snow", "globe-stand", "globe-wifi", "globe-x", "goal", "goal-net", "gofore", "golang",
    "golf-ball-tee", "golf-club", "golf-flag-hole", "goodreads", "goodreads-g", "google",
    "google-drive", "google-pay", "google-play", "google-plus", "google-plus-g", "google-scholar",
    "google-wallet", "gopuram", "gpu", "graduation-cap", "gramophone", "grape", "grapes", "grate",
    "grate-droplet", "gratipay", "grav", "greater-than", "greater-than-equal", "grid", "grid-2",
    "grid-2-plus", "grid-2x2", "grid-2x2-check", "grid-2x2-plus", "grid-2x2-x", "grid-3x2",
    "grid-3x3", "grid-4", "grid-5", "grid-dividers", "grid-horizontal", "grid-round",
    "grid-round-2", "grid-round-2-plus", "grid-round-4", "grid-round-5", "grill", "grill-fire",
    "grill-hot", "grip", "grip-dots", "grip-dots-vertical", "grip-horizontal", "grip-lines",
    "grip-lines-vertical", "grip-vertical", "gripfire", "group", "group-arrows-rotate", "grunt",
    "guarani-sign", "guilded", "guitar", "guitar-electric", "guitars", "gulp", "gun", "gun-slash",
    "gun-squirt", "h", "h1", "h2", "h3", "h4", "h5", "h6", "hacker-news", "hackerrank", "ham",
    "hamburger", "hammer", "hammer-brush", "hammer-crash", "hammer-war", "hamsa", "hand",
    "hand-back-fist", "hand-back-point-down", "hand-back-point-left", "hand-back-point-ribbon",
    "hand-back-point-right", "hand-back-point-up", "hand-coins", "hand-dots",
    "hand-fingers-crossed", "hand-fist", "hand-grab", "hand-heart", "hand-helping", "hand-holding",
    "hand-holding-box", "hand-holding-circle-dollar", "hand-holding-dollar", "hand-holding-droplet",
    "hand-holding-hand", "hand-holding-heart", "hand-holding-magic", "hand-holding-medical",
    "hand-holding-seedling", "hand-holding-skull", "hand-horns", "hand-lizard", "hand-love",
    "hand-metal", "hand-middle-finger", "hand-peace", "hand-platter", "hand-point-down",
    "hand-point-left", "hand-point-ribbon", "hand-point-right", "hand-point-up", "hand-pointer",
    "hand-scissors", "hand-sparkles", "hand-spock", "hand-wave", "handbag", "handcuffs", "hands",
    "hands-asl-interpreting", "hands-bound", "hands-bubbles", "hands-clapping", "hands-holding",
    "hands-holding-child", "hands-holding-circle", "hands-holding-diamond", "hands-holding-dollar",
    "hands-holding-heart", "hands-praying", "handshake", "handshake-angle", "handshake-simple",
    "handshake-simple-slash", "handshake-slash", "hanukiah", "hard-drive", "hard-drive-download",
    "hard-drive-upload", "hard-hat", "hash", "hashnode", "hashtag", "hashtag-lock", "hat-beach",
    "hat-chef", "hat-cowboy", "hat-cowboy-side", "hat-glasses", "hat-santa", "hat-winter",
    "hat-witch", "hat-wizard", "haze", "hd", "hdmi-port", "head-side", "head-side-brain",
    "head-side-cough", "head-side-cough-slash", "head-side-gear", "head-side-goggles",
    "head-side-headphones", "head-side-heart", "head-side-mask", "head-side-medical",
    "head-side-virus", "heading", "heading-1", "heading-2", "heading-3", "heading-4", "heading-5",
    "heading-6", "headphone-off", "headphones", "headphones-simple", "headset", "heart",
    "heart-circle-bolt", "heart-circle-check", "heart-circle-exclamation", "heart-circle-minus",
    "heart-circle-plus", "heart-circle-xmark", "heart-crack", "heart-half", "heart-half-stroke",
    "heart-handshake", "heart-minus", "heart-off", "heart-plus", "heart-pulse", "heat", "heater",
    "helicopter", "helicopter-symbol", "helmet-battle", "helmet-safety", "helmet-un", "hexagon",
    "hexagon-check", "hexagon-divide", "hexagon-exclamation", "hexagon-image", "hexagon-minus",
    "hexagon-nodes", "hexagon-nodes-bolt", "hexagon-plus", "hexagon-vertical-nft",
    "hexagon-vertical-nft-slanted", "hexagon-xmark", "high-definition", "highlighter",
    "highlighter-line", "hill-avalanche", "hill-rockslide", "hippo", "hips", "hire-a-helper",
    "history", "hive", "hockey-mask", "hockey-puck", "hockey-stick-puck", "hockey-sticks",
    "holly-berry", "honey-pot", "hood-cloak", "hooli", "hop", "hop-off", "horizontal-rule",
    "hornbill", "horse", "horse-head", "horse-saddle", "hose", "hose-reel", "hospital",
    "hospital-user", "hospitals", "hot-tub-person", "hotdog", "hotel", "hotjar", "hourglass",
    "hourglass-clock", "hourglass-end", "hourglass-half", "hourglass-start", "house", "house-blank",
    "house-building", "house-chimney", "house-chimney-blank", "house-chimney-crack",
    "house-chimney-heart", "house-chimney-medical", "house-chimney-user", "house-chimney-window",
    "house-circle-check", "house-circle-exclamation", "house-circle-xmark", "house-crack",
    "house-day", "house-fire", "house-flag", "house-flood-water",
    "house-flood-water-circle-arrow-right", "house-heart", "house-laptop", "house-lock",
    "house-medical", "house-medical-circle-check", "house-medical-circle-exclamation",
    "house-medical-circle-xmark", "house-medical-flag", "house-night", "house-person-leave",
    "house-person-return", "house-plug", "house-plus", "house-signal", "house-tree",
    "house-tsunami", "house-turret", "house-user", "house-water", "house-wifi", "house-window",
    "houzz", "hryvnia-sign", "html5", "hubspot", "hundred-points", "hurricane", "hydra", "hyphen",
    "i", "i-cursor", "ice-cream", "ice-cream-bowl", "ice-cream-cone", "ice-skate", "icicles",
    "icons", "id-badge", "id-card", "id-card-clip", "id-card-lanyard", "ideal", "igloo", "image",
    "image-down", "image-landscape", "image-minus", "image-off", "image-play", "image-plus",
    "image-polaroid", "image-polaroid-user", "image-portrait", "image-slash", "image-up",
    "image-upscale", "image-user", "images", "images-user", "imdb", "import", "inbox", "inbox-full",
    "inbox-in", "inbox-out", "inboxes", "indent", "indian-rupee", "indian-rupee-sign", "industry",
    "industry-windows", "infinity", "info", "inhaler", "input-numeric", "input-pipe", "input-text",
    "inspection-panel", "instagram", "instalod", "integral", "intercom", "internet-explorer",
    "interrobang", "intersection", "invision", "ioxhost", "island-tropical", "italic", "itch-io",
    "iteration-ccw", "iteration-cw", "itunes", "itunes-note", "j", "jack-o-lantern", "japanese-yen",
    "jar", "jar-wheat", "java", "jedi", "jedi-order", "jenkins", "jet-fighter", "jet-fighter-up",
    "jira", "joget", "joint", "joomla", "joystick", "js", "jsfiddle", "jug", "jug-bottle",
    "jug-detergent", "jxl", "k", "kaaba", "kaggle", "kanban", "kayak", "kazoo", "kerning", "key",
    "key-round", "key-skeleton", "key-skeleton-left-right", "key-square", "keybase", "keyboard",
    "keyboard-brightness", "keyboard-brightness-low", "keyboard-down", "keyboard-left",
    "keyboard-music", "keyboard-off", "keycdn", "keynote", "khanda", "kickstarter", "kickstarter-k",
    "kidneys", "kip-sign", "kit-medical", "kitchen-set", "kite", "kiwi-bird", "kiwi-fruit", "knife",
    "knife-kitchen", "korvue", "l", "lacrosse-stick", "lacrosse-stick-ball", "lambda", "lamp",
    "lamp-ceiling", "lamp-desk", "lamp-floor", "lamp-street", "lamp-wall-down", "lamp-wall-up",
    "land-mine-on", "land-plot", "landmark", "landmark-dome", "landmark-flag",
    "landmark-magnifying-glass", "language", "languages", "laptop", "laptop-arrow-down",
    "laptop-binary", "laptop-code", "laptop-file", "laptop-medical", "laptop-minimal",
    "laptop-minimal-check", "laptop-mobile", "laptop-slash", "laravel", "lari-sign", "lasso",
    "lasso-select", "lasso-sparkles", "lastfm", "laugh", "layer-group", "layer-minus", "layer-plus",
    "layers", "layers-2", "layers-plus", "layout-dashboard", "layout-grid", "layout-list",
    "layout-panel-left", "layout-panel-top", "layout-template", "leaf", "leaf-heart", "leaf-maple",
    "leaf-oak", "leafy-green", "leanpub", "lectern", "left", "left-from-bracket", "left-from-line",
    "left-long", "left-long-to-line", "left-right", "left-to-bracket", "left-to-line", "lemon",
    "lens-concave", "lens-convex", "less", "less-than", "less-than-equal", "letterboxd", "library",
    "library-big", "life-buoy", "life-ring", "ligature", "light-ceiling", "light-emergency",
    "light-emergency-on", "light-switch", "light-switch-off", "light-switch-on", "lightbulb",
    "lightbulb-cfl", "lightbulb-cfl-on", "lightbulb-dollar", "lightbulb-exclamation",
    "lightbulb-exclamation-on", "lightbulb-gear", "lightbulb-message", "lightbulb-off",
    "lightbulb-on", "lightbulb-slash", "lighthouse", "lights-holiday", "line", "line-columns",
    "line-dot-right-horizontal", "line-height", "line-squiggle", "lines-leaning", "link", "link-2",
    "link-2-off", "link-horizontal", "link-horizontal-slash", "link-simple", "link-simple-slash",
    "link-slash", "linkedin", "linkedin-in", "linode", "linux", "lips", "lira-sign", "list",
    "list-check", "list-checks", "list-chevrons-down-up", "list-chevrons-up-down", "list-collapse",
    "list-dropdown", "list-end", "list-filter", "list-filter-plus", "list-indent-decrease",
    "list-indent-increase", "list-minus", "list-music", "list-ol", "list-ordered", "list-plus",
    "list-radio", "list-restart", "list-start", "list-timeline", "list-todo", "list-tree",
    "list-ul", "list-video", "list-x", "litecoin-sign", "loader", "loader-circle",
    "loader-pinwheel", "lobster", "locate", "locate-fixed", "locate-off", "location-arrow",
    "location-arrow-up", "location-check", "location-crosshairs", "location-crosshairs-slash",
    "location-dot", "location-dot-slash", "location-exclamation", "location-minus", "location-pen",
    "location-pin", "location-pin-lock", "location-pin-slash", "location-plus", "location-question",
    "location-smile", "location-xmark", "lock", "lock-a", "lock-hashtag", "lock-keyhole",
    "lock-keyhole-open", "lock-open", "locust", "log-in", "log-out", "logs", "lollipop", "loveseat",
    "luchador-mask", "luggage", "lungs", "lungs-virus", "lyft", "m", "mace", "magento", "magnet",
    "magnifying-glass", "magnifying-glass-arrow-right", "magnifying-glass-arrows-rotate",
    "magnifying-glass-chart", "magnifying-glass-dollar", "magnifying-glass-location",
    "magnifying-glass-minus", "magnifying-glass-music", "magnifying-glass-play",
    "magnifying-glass-plus", "magnifying-glass-waveform", "mail", "mail-check", "mail-minus",
    "mail-open", "mail-plus", "mail-question-mark", "mail-search", "mail-warning", "mail-x",
    "mailbox", "mailbox-flag-up", "mailchimp", "mails", "manat-sign", "mandalorian", "mandolin",
    "mango", "manhole", "map", "map-location", "map-location-dot", "map-minus", "map-pin",
    "map-pin-check", "map-pin-check-inside", "map-pin-house", "map-pin-minus",
    "map-pin-minus-inside", "map-pin-off", "map-pin-pen", "map-pin-plus", "map-pin-plus-inside",
    "map-pin-x", "map-pin-x-inside", "map-pinned", "map-plus", "markdown", "marker", "mars",
    "mars-and-venus", "mars-and-venus-burst", "mars-double", "mars-stroke", "mars-stroke-right",
    "mars-stroke-up", "martini", "martini-glass", "martini-glass-citrus", "martini-glass-empty",
    "mask", "mask-face", "mask-snorkel", "mask-ventilator", "masks-theater", "mastodon",
    "mattress-pillow", "maxcdn", "maximize", "maximize-2", "mdb", "meat", "medal", "medapps",
    "medium", "medrt", "meetup", "megaphone", "megaphone-off", "megaport", "meh", "melon",
    "melon-slice", "memo", "memo-circle-check", "memo-circle-info", "memo-pad", "memory",
    "memory-stick", "mendeley", "menorah", "menu", "mercury", "merge", "message",
    "message-arrow-down", "message-arrow-up", "message-arrow-up-right", "message-bot",
    "message-captions", "message-check", "message-circle", "message-circle-check",
    "message-circle-code", "message-circle-dashed", "message-circle-heart", "message-circle-more",
    "message-circle-off", "message-circle-plus", "message-circle-question-mark",
    "message-circle-reply", "message-circle-warning", "message-circle-x", "message-code",
    "message-dollar", "message-dots", "message-exclamation", "message-heart", "message-image",
    "message-lines", "message-medical", "message-middle", "message-middle-top", "message-minus",
    "message-music", "message-pen", "message-plus", "message-question", "message-quote",
    "message-slash", "message-smile", "message-sms", "message-square", "message-square-check",
    "message-square-code", "message-square-dashed", "message-square-diff", "message-square-dot",
    "message-square-heart", "message-square-lock", "message-square-more", "message-square-off",
    "message-square-plus", "message-square-quote", "message-square-reply", "message-square-share",
    "message-square-text", "message-square-warning", "message-square-x", "message-text",
    "message-xmark", "messages", "messages-dollar", "messages-question", "messages-square", "meta",
    "meteor", "meter", "meter-bolt", "meter-droplet", "meter-fire", "metronome", "mic", "mic-off",
    "mic-vocal", "microblog", "microchip", "microchip-ai", "microphone", "microphone-lines",
    "microphone-lines-slash", "microphone-slash", "microphone-stand", "microscope", "microsoft",
    "microwave", "milestone", "milk", "milk-off", "mill-sign", "minimize", "minimize-2", "mintbit",
    "minus", "mirror-rectangular", "mirror-round", "mistletoe", "mitten", "mix", "mixcloud",
    "mixer", "mizuni", "mobile", "mobile-button", "mobile-notch", "mobile-retro", "mobile-screen",
    "mobile-screen-button", "mobile-signal", "mobile-signal-out", "modx", "monero", "money-bill",
    "money-bill-1", "money-bill-1-wave", "money-bill-simple", "money-bill-simple-wave",
    "money-bill-transfer", "money-bill-trend-up", "money-bill-wave", "money-bill-wheat",
    "money-bills", "money-bills-simple", "money-check", "money-check-dollar",
    "money-check-dollar-pen", "money-check-pen", "money-from-bracket", "money-simple-from-bracket",
    "monitor", "monitor-check", "monitor-cloud", "monitor-cog", "monitor-dot", "monitor-down",
    "monitor-off", "monitor-pause", "monitor-play", "monitor-smartphone", "monitor-speaker",
    "monitor-stop", "monitor-up", "monitor-waveform", "monitor-x", "monkey", "monument", "moon",
    "moon-cloud", "moon-over-sun", "moon-star", "moon-stars", "moped", "mortar-pestle", "mosque",
    "mosquito", "mosquito-net", "motorbike", "motorcycle", "mound", "mountain", "mountain-city",
    "mountain-snow", "mountain-sun", "mountains", "mouse", "mouse-field", "mouse-left", "mouse-off",
    "mouse-pointer", "mouse-pointer-2", "mouse-pointer-2-off", "mouse-pointer-ban",
    "mouse-pointer-click", "mouse-right", "move", "move-3d", "move-diagonal", "move-diagonal-2",
    "move-down", "move-down-left", "move-down-right", "move-horizontal", "move-left", "move-right",
    "move-up", "move-up-left", "move-up-right", "move-vertical", "mp3-player", "mug", "mug-hot",
    "mug-marshmallows", "mug-saucer", "mug-tea", "mug-tea-saucer", "mushroom", "music", "music-2",
    "music-3", "music-4", "music-magnifying-glass", "music-note", "music-note-slash", "music-slash",
    "mustache", "n", "naira-sign", "napster", "narwhal", "navigation", "navigation-2",
    "navigation-2-off", "navigation-off", "neos", "nesting-dolls", "network", "network-wired",
    "neuter", "newspaper", "nfc", "nfc-directional", "nfc-lock", "nfc-magnifying-glass", "nfc-pen",
    "nfc-signal", "nfc-slash", "nfc-symbol", "nfc-trash", "nimblr", "node", "node-js", "non-binary",
    "nose", "not-equal", "notdef", "note", "note-medical", "note-sticky", "notebook",
    "notebook-pen", "notebook-tabs", "notebook-text", "notepad-text", "notepad-text-dashed",
    "notes", "notes-medical", "npm", "ns8", "nut", "nut-off", "nutritionix", "o", "object-exclude",
    "object-group", "object-intersect", "object-subtract", "object-ungroup", "object-union",
    "objects-align-bottom", "objects-align-center-horizontal", "objects-align-center-vertical",
    "objects-align-left", "objects-align-right", "objects-align-top", "objects-column", "octagon",
    "octagon-alert", "octagon-check", "octagon-divide", "octagon-exclamation", "octagon-minus",
    "octagon-pause", "octagon-plus", "octagon-x", "octagon-xmark", "octopus", "octopus-deploy",
    "odnoklassniki", "odysee", "oil-can", "oil-can-drip", "oil-temperature", "oil-well",
    "old-republic", "olive", "olive-branch", "om", "omega", "onion", "opencart", "openid",
    "opensuse", "opera", "optin-monster", "option", "orbit", "orcid", "origami", "ornament", "osi",
    "otter", "outdent", "outlet", "oven", "overline", "p", "package", "package-2", "package-check",
    "package-minus", "package-open", "package-plus", "package-search", "package-x", "padlet",
    "page", "page-caret-down", "page-caret-up", "page4", "pagelines", "pager", "paint-bucket",
    "paint-roller", "paintbrush", "paintbrush-fine", "paintbrush-pencil", "paintbrush-vertical",
    "palette", "palfed", "pallet", "pallet-box", "pallet-boxes", "pan-food", "pan-frying",
    "pancakes", "panda", "panel-bottom", "panel-bottom-close", "panel-bottom-dashed",
    "panel-bottom-open", "panel-ews", "panel-fire", "panel-left", "panel-left-close",
    "panel-left-dashed", "panel-left-open", "panel-left-right-dashed", "panel-right",
    "panel-right-close", "panel-right-dashed", "panel-right-open", "panel-top",
    "panel-top-bottom-dashed", "panel-top-close", "panel-top-dashed", "panel-top-open",
    "panels-left-bottom", "panels-right-bottom", "panels-top-left", "panorama", "paper-plane",
    "paper-plane-top", "paperclip", "paperclip-vertical", "parachute-box", "paragraph",
    "paragraph-left", "parentheses", "parking-meter", "party-bell", "party-horn", "party-popper",
    "passport", "paste", "patreon", "pause", "paw", "paw-claws", "paw-print", "paw-simple",
    "paypal", "pc-case", "peace", "peach", "peanut", "peanuts", "peapod", "pear", "pedestal",
    "pegasus", "pen", "pen-circle", "pen-clip", "pen-clip-slash", "pen-fancy", "pen-fancy-slash",
    "pen-field", "pen-line", "pen-nib", "pen-nib-slash", "pen-off", "pen-paintbrush", "pen-ruler",
    "pen-slash", "pen-swirl", "pen-to-square", "pen-tool", "pencil", "pencil-line",
    "pencil-mechanical", "pencil-off", "pencil-ruler", "pencil-slash", "pentagon", "people",
    "people-arrows", "people-carry-box", "people-dress", "people-dress-simple", "people-group",
    "people-line", "people-pants", "people-pants-simple", "people-pulling", "people-robbery",
    "people-roof", "people-simple", "pepper", "pepper-hot", "perbyte", "percent", "period",
    "periscope", "person", "person-arrow-down-to-line", "person-arrow-up-from-line",
    "person-biking", "person-biking-mountain", "person-booth", "person-breastfeeding",
    "person-burst", "person-cane", "person-carry-box", "person-chalkboard", "person-circle-check",
    "person-circle-exclamation", "person-circle-minus", "person-circle-plus",
    "person-circle-question", "person-circle-xmark", "person-digging", "person-dolly",
    "person-dolly-empty", "person-dots-from-line", "person-dress", "person-dress-burst",
    "person-dress-fairy", "person-dress-simple", "person-drowning", "person-fairy",
    "person-falling", "person-falling-burst", "person-from-portal", "person-half-dress",
    "person-harassing", "person-hiking", "person-military-pointing", "person-military-rifle",
    "person-military-to-person", "person-pinball", "person-praying", "person-pregnant",
    "person-rays", "person-rifle", "person-running", "person-running-fast", "person-seat",
    "person-seat-reclined", "person-shelter", "person-sign", "person-simple", "person-skating",
    "person-ski-jumping", "person-ski-lift", "person-skiing", "person-skiing-nordic",
    "person-sledding", "person-snowboarding", "person-snowmobiling", "person-standing",
    "person-swimming", "person-through-window", "person-to-door", "person-to-portal",
    "person-walking", "person-walking-arrow-loop-left", "person-walking-arrow-right",
    "person-walking-dashed-line-arrow-right", "person-walking-luggage", "person-walking-with-cane",
    "peseta-sign", "peso-sign", "phabricator", "philippine-peso", "phoenix-framework",
    "phoenix-squadron", "phone", "phone-arrow-down-left", "phone-arrow-right",
    "phone-arrow-up-right", "phone-call", "phone-flip", "phone-forwarded", "phone-hangup",
    "phone-incoming", "phone-intercom", "phone-missed", "phone-off", "phone-office",
    "phone-outgoing", "phone-plus", "phone-rotary", "phone-slash", "phone-volume", "phone-xmark",
    "photo-film", "photo-film-music", "php", "pi", "piano", "piano-keyboard", "pickaxe",
    "pickleball", "picture-in-picture", "picture-in-picture-2", "pie", "pied-piper",
    "pied-piper-alt", "pied-piper-hat", "pied-piper-pp", "pig", "piggy-bank", "pilcrow",
    "pilcrow-left", "pilcrow-right", "pill", "pill-bottle", "pills", "pin", "pin-off", "pinata",
    "pinball", "pineapple", "pinterest", "pinterest-p", "pipe", "pipe-circle-check", "pipe-collar",
    "pipe-section", "pipe-smoking", "pipe-valve", "pipette", "pix", "pixiv", "pizza", "pizza-slice",
    "place-of-worship", "plane", "plane-arrival", "plane-circle-check", "plane-circle-exclamation",
    "plane-circle-xmark", "plane-departure", "plane-engines", "plane-landing", "plane-lock",
    "plane-prop", "plane-slash", "plane-tail", "plane-takeoff", "plane-up", "plane-up-slash",
    "planet-moon", "planet-ringed", "plant-wilt", "plate-utensils", "plate-wheat", "play",
    "play-pause", "playstation", "plug", "plug-2", "plug-circle-bolt", "plug-circle-check",
    "plug-circle-exclamation", "plug-circle-minus", "plug-circle-plus", "plug-circle-xmark",
    "plug-zap", "plus", "plus-large", "plus-minus", "pocket", "pocket-knife", "podcast", "podium",
    "podium-star", "pointer", "pointer-off", "police-box", "poll-people", "pompebled", "poo",
    "poo-storm", "pool-8-ball", "poop", "popcorn", "popsicle", "pot-food", "potato",
    "pound-sterling", "power", "power-off", "prescription", "prescription-bottle",
    "prescription-bottle-medical", "prescription-bottle-pill", "presentation",
    "presentation-screen", "pretzel", "print", "print-magnifying-glass", "print-slash", "printer",
    "printer-check", "printer-x", "product-hunt", "projector", "proportions", "pump",
    "pump-medical", "pump-soap", "pumpkin", "pushed", "puzzle", "puzzle-piece",
    "puzzle-piece-simple", "pyramid", "python", "q", "qq", "qr-code", "qrcode", "question",
    "quinscape", "quora", "quote", "quote-left", "quote-right", "quotes", "r", "r-project",
    "rabbit", "rabbit-running", "raccoon", "racquet", "radar", "radiation", "radical", "radio",
    "radio-receiver", "radio-tower", "radio-tuner", "radius", "rail-symbol", "rainbow", "raindrops",
    "ram", "ramp-loading", "ranking-star", "raspberry-pi", "rat", "ratio", "ravelry", "raygun",
    "react", "reacteurope", "readme", "rebel", "receipt", "receipt-cent", "receipt-euro",
    "receipt-indian-rupee", "receipt-japanese-yen", "receipt-pound-sterling",
    "receipt-russian-ruble", "receipt-swiss-franc", "receipt-text", "receipt-turkish-lira",
    "record-vinyl", "rectangle", "rectangle-ad", "rectangle-barcode", "rectangle-circle",
    "rectangle-code", "rectangle-ellipsis", "rectangle-goggles", "rectangle-history",
    "rectangle-history-circle-plus", "rectangle-history-circle-user", "rectangle-horizontal",
    "rectangle-list", "rectangle-pro", "rectangle-terminal", "rectangle-vertical",
    "rectangle-vertical-history", "rectangle-wide", "rectangle-xmark", "rectangles-mixed",
    "recycle", "red-river", "reddit", "reddit-alien", "redhat", "redo", "redo-2", "redo-dot",
    "reel", "reflect-both", "reflect-horizontal", "reflect-vertical", "refresh-ccw",
    "refresh-ccw-dot", "refresh-cw", "refresh-cw-off", "refrigerator", "regex", "registered",
    "remove-formatting", "renren", "repeat", "repeat-1", "repeat-2", "replace", "replace-all",
    "reply", "reply-all", "reply-clock", "replyd", "republican", "researchgate", "resolving",
    "restroom", "restroom-simple", "retweet", "rev", "rewind", "rhombus", "ribbon", "right",
    "right-from-bracket", "right-from-line", "right-left", "right-left-large", "right-long",
    "right-long-to-line", "right-to-bracket", "right-to-line", "ring", "ring-diamond",
    "rings-wedding", "road", "road-barrier", "road-bridge", "road-circle-check",
    "road-circle-exclamation", "road-circle-xmark", "road-lock", "road-spikes", "robot",
    "robot-astromech", "rocket", "rocket-launch", "rocketchat", "rocking-chair", "rockrms",
    "roller-coaster", "rose", "rotate", "rotate-3d", "rotate-ccw", "rotate-ccw-key",
    "rotate-ccw-square", "rotate-cw", "rotate-cw-square", "rotate-exclamation", "rotate-left",
    "rotate-reverse", "rotate-right", "route", "route-highway", "route-interstate", "route-off",
    "router", "rows-2", "rows-3", "rows-4", "rss", "ruble-sign", "rug", "rugby-ball", "ruler",
    "ruler-combined", "ruler-dimension-line", "ruler-horizontal", "ruler-triangle",
    "ruler-vertical", "rupee-sign", "rupiah-sign", "russian-ruble", "rust", "rv", "s", "sack",
    "sack-dollar", "sack-xmark", "safari", "sailboat", "salad", "salesforce", "salt-shaker",
    "sandwich", "sass", "satellite", "satellite-dish", "saudi-riyal", "sausage", "save", "save-all",
    "save-off", "saxophone", "saxophone-fire", "scale", "scale-3d", "scale-balanced",
    "scale-unbalanced", "scale-unbalanced-flip", "scaling", "scalpel", "scalpel-line-dashed",
    "scan", "scan-barcode", "scan-eye", "scan-face", "scan-heart", "scan-line", "scan-qr-code",
    "scan-search", "scan-text", "scanner-gun", "scanner-image", "scanner-keyboard",
    "scanner-touchscreen", "scarecrow", "scarf", "schlix", "school", "school-circle-check",
    "school-circle-exclamation", "school-circle-xmark", "school-flag", "school-lock", "scissors",
    "scissors-line-dashed", "scooter", "screen-share", "screen-share-off", "screen-users",
    "screencast", "screenpal", "screwdriver", "screwdriver-wrench", "scribble", "scribd", "scroll",
    "scroll-old", "scroll-text", "scroll-torah", "scrubber", "scythe", "sd-card", "sd-cards",
    "seal", "seal-exclamation", "seal-question", "search", "search-alert", "search-check",
    "search-code", "search-slash", "search-x", "searchengin", "seat-airline", "section", "seedling",
    "sellcast", "sellsy", "semicolon", "send", "send-back", "send-backward", "send-horizontal",
    "send-to-back", "sensor", "sensor-cloud", "sensor-fire", "sensor-on",
    "sensor-triangle-exclamation", "separator-horizontal", "separator-vertical", "server",
    "server-cog", "server-crash", "server-off", "servicestack", "settings", "settings-2", "shapes",
    "share", "share-2", "share-all", "share-from-square", "share-nodes", "sheep", "sheet",
    "sheet-plastic", "shekel-sign", "shell", "shelves", "shelves-empty", "shelving-unit", "shield",
    "shield-alert", "shield-ban", "shield-cat", "shield-check", "shield-cross", "shield-dog",
    "shield-ellipsis", "shield-exclamation", "shield-half", "shield-halved", "shield-heart",
    "shield-keyhole", "shield-minus", "shield-off", "shield-plus", "shield-quartered",
    "shield-question-mark", "shield-slash", "shield-user", "shield-virus", "shield-x",
    "shield-xmark", "ship", "ship-wheel", "shirt", "shirt-long-sleeve", "shirt-running",
    "shirt-tank-top", "shirtsinbulk", "shish-kebab", "shoe-prints", "shoelace", "shop", "shop-lock",
    "shop-slash", "shopify", "shopping-bag", "shopping-basket", "shopping-cart", "shopware",
    "shovel", "shovel-snow", "shower", "shower-down", "shower-head", "shredder", "shrimp", "shrink",
    "shrub", "shuffle", "shutters", "shuttle-space", "shuttlecock", "sickle", "sidebar",
    "sidebar-flip", "sigma", "sign-hanging", "sign-post", "sign-posts", "sign-posts-wrench",
    "signal", "signal-bars", "signal-bars-fair", "signal-bars-good", "signal-bars-slash",
    "signal-bars-weak", "signal-fair", "signal-good", "signal-high", "signal-low", "signal-medium",
    "signal-messenger", "signal-slash", "signal-stream", "signal-stream-slash", "signal-strong",
    "signal-weak", "signal-zero", "signature", "signature-lock", "signature-slash", "signpost",
    "signpost-big", "signs-post", "sim-card", "sim-cards", "simplybuilt", "sink", "siren",
    "siren-on", "sistrix", "sitemap", "sith", "sitrox", "skeleton", "skeleton-ribs", "sketch",
    "ski-boot", "ski-boot-ski", "skip-back", "skip-forward", "skull", "skull-cow",
    "skull-crossbones", "skyatlas", "skype", "slack", "slash", "slash-back", "slash-forward",
    "sleigh", "slice", "slider", "sliders", "sliders-horizontal", "sliders-simple", "sliders-up",
    "sliders-vertical", "slideshare", "slot-machine", "smartphone", "smartphone-charging",
    "smartphone-nfc", "smile", "smile-plus", "smog", "smoke", "smoking", "snail", "snake",
    "snapchat", "snooze", "snow-blowing", "snowflake", "snowflake-droplets", "snowflakes",
    "snowman", "snowman-head", "snowplow", "soap", "soap-dispenser-droplet", "socks", "sofa",
    "soft-serve", "solar-panel", "solar-system", "sort", "sort-down", "sort-up", "soundcloud",
    "soup", "sourcetree", "spa", "space", "space-awesome", "space-station-moon",
    "space-station-moon-construction", "spade", "spaghetti-monster-flying", "sparkle", "sparkles",
    "speakap", "speaker", "speaker-deck", "speakers", "speech", "spell-check", "spell-check-2",
    "spider", "spider-black-widow", "spider-web", "spinner", "spinner-scale", "spinner-third",
    "spline", "spline-pointer", "split", "splotch", "spool", "spoon", "sportsball", "spotify",
    "spotlight", "spray-can", "spray-can-sparkles", "sprinkler", "sprinkler-ceiling", "sprout",
    "square", "square-0", "square-1", "square-2", "square-3", "square-4", "square-5", "square-6",
    "square-7", "square-8", "square-9", "square-a", "square-a-lock", "square-activity",
    "square-ampersand", "square-arrow-down", "square-arrow-down-left", "square-arrow-down-right",
    "square-arrow-left", "square-arrow-out-down-left", "square-arrow-out-down-right",
    "square-arrow-out-up-left", "square-arrow-out-up-right", "square-arrow-right",
    "square-arrow-right-enter", "square-arrow-right-exit", "square-arrow-up",
    "square-arrow-up-left", "square-arrow-up-right", "square-asterisk", "square-b",
    "square-behance", "square-binary", "square-bluesky", "square-bolt",
    "square-bottom-dashed-scissors", "square-c", "square-caret-down", "square-caret-left",
    "square-caret-right", "square-caret-up", "square-centerline-dashed-horizontal",
    "square-centerline-dashed-vertical", "square-chart-gantt", "square-check", "square-check-big",
    "square-chevron-down", "square-chevron-left", "square-chevron-right", "square-chevron-up",
    "square-code", "square-d", "square-dashed", "square-dashed-bottom", "square-dashed-bottom-code",
    "square-dashed-circle-plus", "square-dashed-kanban", "square-dashed-mouse-pointer",
    "square-dashed-top-solid", "square-divide", "square-dollar", "square-dot", "square-down",
    "square-down-left", "square-down-right", "square-dribbble", "square-e", "square-ellipsis",
    "square-ellipsis-vertical", "square-envelope", "square-equal", "square-exclamation", "square-f",
    "square-facebook", "square-font-awesome", "square-font-awesome-stroke", "square-fragile",
    "square-full", "square-function", "square-g", "square-git", "square-github", "square-gitlab",
    "square-google-plus", "square-h", "square-hacker-news", "square-heart", "square-i",
    "square-info", "square-instagram", "square-j", "square-js", "square-k", "square-kanban",
    "square-l", "square-lastfm", "square-left", "square-letterboxd", "square-library",
    "square-list", "square-m", "square-menu", "square-minus", "square-mouse-pointer", "square-n",
    "square-nfi", "square-o", "square-odnoklassniki", "square-p", "square-parking",
    "square-parking-off", "square-parking-slash", "square-pause", "square-pen", "square-percent",
    "square-person-confined", "square-phone", "square-phone-flip", "square-phone-hangup",
    "square-pi", "square-pied-piper", "square-pilcrow", "square-pinterest", "square-play",
    "square-plus", "square-poll-horizontal", "square-poll-vertical", "square-power", "square-q",
    "square-quarters", "square-question", "square-quote", "square-r", "square-radical",
    "square-reddit", "square-right", "square-ring", "square-root", "square-root-variable",
    "square-round-corner", "square-rss", "square-s", "square-scissors", "square-share-nodes",
    "square-sigma", "square-slash", "square-sliders", "square-sliders-vertical", "square-small",
    "square-snapchat", "square-split-horizontal", "square-split-vertical", "square-square",
    "square-stack", "square-star", "square-steam", "square-stop", "square-t", "square-terminal",
    "square-this-way-up", "square-threads", "square-tumblr", "square-twitter", "square-u",
    "square-up", "square-up-left", "square-up-right", "square-upwork", "square-user",
    "square-user-round", "square-v", "square-viadeo", "square-vimeo", "square-virus", "square-w",
    "square-web-awesome", "square-web-awesome-stroke", "square-whatsapp", "square-x",
    "square-x-twitter", "square-xing", "square-xmark", "square-y", "square-youtube", "square-z",
    "squares-exclude", "squares-intersect", "squares-subtract", "squares-unite", "squarespace",
    "squid", "squircle", "squircle-dashed", "squirrel", "stack-exchange", "stack-overflow",
    "stackpath", "staff", "staff-snake", "stairs", "stamp", "standard-definition", "stapler",
    "star", "star-and-crescent", "star-christmas", "star-exclamation", "star-half",
    "star-half-stroke", "star-of-david", "star-of-life", "star-off", "star-sharp",
    "star-sharp-half", "star-sharp-half-stroke", "star-shooting", "starfighter",
    "starfighter-twin-ion-engine", "starfighter-twin-ion-engine-advanced", "stars", "starship",
    "starship-freighter", "staylinked", "steak", "steam", "steam-symbol", "steering-wheel",
    "step-back", "step-forward", "sterling-sign", "stethoscope", "sticker", "sticker-mule",
    "sticky-note", "stocking", "stomach", "stone", "stop", "stopwatch", "stopwatch-20", "store",
    "store-lock", "store-slash", "strava", "strawberry", "street-view", "stretch-horizontal",
    "stretch-vertical", "stretcher", "strikethrough", "stripe", "stripe-s", "stroopwafel",
    "stubber", "studiovinari", "stumbleupon", "stumbleupon-circle", "subscript", "subtitles",
    "subtitles-slash", "suitcase", "suitcase-medical", "suitcase-rolling", "sun", "sun-bright",
    "sun-cloud", "sun-dim", "sun-dust", "sun-haze", "sun-medium", "sun-moon", "sun-plant-wilt",
    "sun-snow", "sunglasses", "sunrise", "sunset", "superpowers", "superscript", "supple", "suse",
    "sushi", "sushi-roll", "swap", "swap-arrows", "swatch-book", "swatchbook", "swift",
    "swiss-franc", "switch-camera", "sword", "sword-laser", "sword-laser-alt", "swords",
    "swords-laser", "symbols", "symfony", "synagogue", "syringe", "t", "t-rex", "table", "table-2",
    "table-cells", "table-cells-column-lock", "table-cells-column-unlock", "table-cells-large",
    "table-cells-lock", "table-cells-merge", "table-cells-row-lock", "table-cells-row-unlock",
    "table-cells-split", "table-cells-unlock", "table-columns", "table-columns-split",
    "table-layout", "table-list", "table-of-contents", "table-picnic", "table-pivot",
    "table-properties", "table-rows", "table-rows-split", "table-tennis-paddle-ball", "table-tree",
    "tablet", "tablet-button", "tablet-rugged", "tablet-screen", "tablet-screen-button",
    "tablet-smartphone", "tablets", "tachograph-digital", "taco", "tag", "tags", "tally", "tally-1",
    "tally-2", "tally-3", "tally-4", "tally-5", "tamale", "tangent", "tank-water", "tape", "target",
    "tarp", "tarp-droplet", "taxi", "taxi-bus", "teamspeak", "teddy-bear", "teeth", "teeth-open",
    "telegram", "telescope", "temperature-arrow-down", "temperature-arrow-up", "temperature-empty",
    "temperature-full", "temperature-half", "temperature-high", "temperature-list",
    "temperature-low", "temperature-quarter", "temperature-snow", "temperature-sun",
    "temperature-three-quarters", "tencent-weibo", "tenge-sign", "tennis-ball", "tent",
    "tent-arrow-down-to-line", "tent-arrow-left-right", "tent-arrow-turn-left", "tent-arrows-down",
    "tent-double-peak", "tent-tree", "tents", "terminal", "test-tube", "test-tube-diagonal",
    "test-tubes", "text", "text-align-center", "text-align-end", "text-align-justify",
    "text-align-start", "text-cursor", "text-cursor-input", "text-height", "text-initial",
    "text-quote", "text-search", "text-select", "text-size", "text-slash", "text-width",
    "text-wrap", "the-red-yeti", "theater", "themeco", "themeisle", "thermometer",
    "thermometer-snowflake", "thermometer-sun", "theta", "think-peaks", "thought-bubble", "threads",
    "thumbs-down", "thumbs-up", "thumbtack", "thumbtack-slash", "tick", "ticket", "ticket-airline",
    "ticket-check", "ticket-minus", "ticket-percent", "ticket-perforated", "ticket-plus",
    "ticket-simple", "ticket-slash", "ticket-x", "tickets", "tickets-airline", "tickets-perforated",
    "tickets-plane", "tickets-simple", "tiktok", "tilde", "timeline", "timeline-arrow", "timer",
    "timer-off", "timer-reset", "tire", "tire-flat", "tire-pressure-warning", "tire-rugged",
    "toggle-large-off", "toggle-large-on", "toggle-left", "toggle-off", "toggle-on", "toggle-right",
    "toilet", "toilet-paper", "toilet-paper-blank", "toilet-paper-blank-under",
    "toilet-paper-check", "toilet-paper-slash", "toilet-paper-under", "toilet-paper-under-slash",
    "toilet-paper-xmark", "toilet-portable", "toilets-portable", "tomato", "tombstone",
    "tombstone-blank", "tool-case", "toolbox", "tooth", "toothbrush", "torii-gate", "tornado",
    "torus", "touchpad", "touchpad-off", "towel-rack", "tower-broadcast", "tower-cell",
    "tower-control", "tower-observation", "toy-brick", "tractor", "trade-federation", "trademark",
    "traffic-cone", "traffic-light", "traffic-light-go", "traffic-light-slow", "traffic-light-stop",
    "trailer", "train", "train-front", "train-front-tunnel", "train-subway", "train-subway-tunnel",
    "train-track", "train-tram", "train-tunnel", "tram-front", "transformer-bolt", "transgender",
    "transporter", "transporter-1", "transporter-2", "transporter-3", "transporter-4",
    "transporter-5", "transporter-6", "transporter-7", "transporter-empty", "trash", "trash-2",
    "trash-arrow-up", "trash-can", "trash-can-arrow-up", "trash-can-check", "trash-can-clock",
    "trash-can-list", "trash-can-plus", "trash-can-slash", "trash-can-undo", "trash-can-xmark",
    "trash-check", "trash-clock", "trash-list", "trash-plus", "trash-slash", "trash-undo",
    "trash-xmark", "treasure-chest", "tree", "tree-christmas", "tree-city", "tree-deciduous",
    "tree-decorated", "tree-large", "tree-palm", "tree-pine", "trees", "trello", "trending-down",
    "trending-up", "trending-up-down", "triangle", "triangle-alert", "triangle-dashed",
    "triangle-exclamation", "triangle-instrument", "triangle-person-digging", "triangle-right",
    "tricycle", "tricycle-adult", "trillium", "trophy", "trophy-star", "trowel", "trowel-bricks",
    "truck", "truck-arrow-right", "truck-bolt", "truck-clock", "truck-container",
    "truck-container-empty", "truck-droplet", "truck-electric", "truck-fast", "truck-field",
    "truck-field-un", "truck-fire", "truck-flatbed", "truck-front", "truck-ladder", "truck-medical",
    "truck-monster", "truck-moving", "truck-pickup", "truck-plane", "truck-plow", "truck-ramp",
    "truck-ramp-box", "truck-ramp-couch", "truck-tow", "truck-utensils", "trumpet", "tty",
    "tty-answer", "tugrik-sign", "tumblr", "turkey", "turkish-lira", "turkish-lira-sign",
    "turn-down", "turn-down-left", "turn-down-right", "turn-left", "turn-left-down", "turn-left-up",
    "turn-right", "turn-up", "turntable", "turtle", "tv", "tv-minimal", "tv-minimal-play",
    "tv-music", "tv-retro", "twitch", "twitter", "type", "type-outline", "typewriter", "typo3", "u",
    "uber", "ubuntu", "ufo", "ufo-beam", "uikit", "umbraco", "umbrella", "umbrella-beach",
    "umbrella-off", "umbrella-simple", "uncharted", "underline", "undo", "undo-2", "undo-dot",
    "unfold-horizontal", "unfold-vertical", "ungroup", "unicorn", "uniform-martial-arts", "union",
    "uniregistry", "unity", "universal-access", "university", "unlink", "unlink-2", "unlock",
    "unlock-keyhole", "unplug", "unsplash", "untappd", "up", "up-down", "up-down-left-right",
    "up-from-bracket", "up-from-dotted-line", "up-from-line", "up-left", "up-long", "up-right",
    "up-right-and-down-left-from-center", "up-right-from-square", "up-to-bracket",
    "up-to-dotted-line", "up-to-line", "upload", "ups", "upwork", "usb", "usb-drive", "user",
    "user-alien", "user-astronaut", "user-beard-bolt", "user-bounty-hunter", "user-check",
    "user-chef", "user-clock", "user-cog", "user-cowboy", "user-crown", "user-doctor",
    "user-doctor-hair", "user-doctor-hair-long", "user-doctor-message", "user-gear",
    "user-graduate", "user-group", "user-group-crown", "user-group-simple", "user-hair",
    "user-hair-buns", "user-hair-long", "user-hair-mullet", "user-headset", "user-helmet-safety",
    "user-hoodie", "user-injured", "user-key", "user-large", "user-large-slash", "user-lock",
    "user-magnifying-glass", "user-minus", "user-music", "user-ninja", "user-nurse",
    "user-nurse-hair", "user-nurse-hair-long", "user-pen", "user-pilot", "user-pilot-tie",
    "user-plus", "user-police", "user-police-tie", "user-robot", "user-robot-xmarks", "user-round",
    "user-round-check", "user-round-cog", "user-round-key", "user-round-minus", "user-round-pen",
    "user-round-plus", "user-round-search", "user-round-x", "user-search", "user-secret",
    "user-shakespeare", "user-shield", "user-slash", "user-star", "user-tag", "user-tie",
    "user-tie-hair", "user-tie-hair-long", "user-unlock", "user-visor", "user-vneck",
    "user-vneck-hair", "user-vneck-hair-long", "user-x", "user-xmark", "users",
    "users-between-lines", "users-gear", "users-line", "users-medical", "users-rays",
    "users-rectangle", "users-round", "users-slash", "users-viewfinder", "usps", "ussunnah",
    "utensils", "utensils-crossed", "utensils-slash", "utility-pole", "utility-pole-double", "v",
    "vaadin", "vacuum", "vacuum-robot", "value-absolute", "van", "van-shuttle", "variable", "vault",
    "vector-circle", "vector-polygon", "vector-square", "vegan", "venetian-mask", "vent-damper",
    "venus", "venus-and-mars", "venus-double", "venus-mars", "vest", "vest-patches", "viacoin",
    "viadeo", "vial", "vial-circle-check", "vial-virus", "vials", "viber", "vibrate", "vibrate-off",
    "video", "video-arrow-down-left", "video-arrow-up-right", "video-off", "video-plus",
    "video-slash", "videotape", "view", "vihara", "vimeo", "vimeo-v", "vine", "violin", "virus",
    "virus-covid", "virus-covid-slash", "virus-slash", "viruses", "vk", "vnv", "voicemail",
    "volcano", "volleyball", "volume", "volume-1", "volume-2", "volume-high", "volume-low",
    "volume-off", "volume-slash", "volume-x", "volume-xmark", "vote", "vr-cardboard", "vuejs", "w",
    "waffle", "wagon-covered", "walker", "walkie-talkie", "wallet", "wallet-cards",
    "wallet-minimal", "wallpaper", "wand", "wand-magic", "wand-magic-sparkles", "wand-sparkles",
    "warehouse", "warehouse-full", "washing-machine", "watch", "watch-apple", "watch-calculator",
    "watch-fitness", "watch-smart", "watchman-monitoring", "water", "water-arrow-down",
    "water-arrow-up", "water-ladder", "watermelon-slice", "wave", "wave-pulse", "wave-sine",
    "wave-square", "wave-triangle", "waveform", "waveform-lines", "waves", "waves-arrow-down",
    "waves-arrow-up", "waves-ladder", "waves-sine", "waypoints", "waze", "web-awesome", "webcam",
    "webflow", "webhook", "webhook-off", "weebly", "weibo", "weight", "weight-hanging",
    "weight-scale", "weight-tilde", "weixin", "whale", "whatsapp", "wheat", "wheat-awn",
    "wheat-awn-circle-exclamation", "wheat-awn-slash", "wheat-off", "wheat-slash", "wheelchair",
    "wheelchair-move", "whiskey-glass", "whiskey-glass-ice", "whistle", "whmcs", "whole-word",
    "wifi", "wifi-cog", "wifi-exclamation", "wifi-fair", "wifi-high", "wifi-low", "wifi-off",
    "wifi-pen", "wifi-slash", "wifi-sync", "wifi-weak", "wifi-zero", "wikipedia-w", "wind",
    "wind-arrow-down", "wind-turbine", "wind-warning", "window", "window-flip", "window-frame",
    "window-frame-open", "window-maximize", "window-minimize", "window-restore", "windows",
    "windsock", "wine", "wine-bottle", "wine-glass", "wine-glass-crack", "wine-glass-empty",
    "wine-off", "wirsindhandwerk", "wix", "wizards-of-the-coast", "wodu", "wolf-pack-battalion",
    "won-sign", "wordpress", "wordpress-simple", "workflow", "worm", "wpbeginner", "wpexplorer",
    "wpforms", "wpressr", "wreath", "wreath-laurel", "wrench", "wrench-simple", "x", "x-line-top",
    "x-ray", "x-twitter", "xbox", "xing", "xmark", "xmark-large", "xmark-to-slot", "xmarks-lines",
    "y", "y-combinator", "yahoo", "yammer", "yandex", "yandex-international", "yarn", "yelp",
    "yen-sign", "yin-yang", "yoast", "youtube", "z", "zap", "zap-off", "zhihu", "zodiac-aquarius",
    "zodiac-aries", "zodiac-cancer", "zodiac-capricorn", "zodiac-gemini", "zodiac-leo",
    "zodiac-libra", "zodiac-ophiuchus", "zodiac-pisces", "zodiac-sagittarius", "zodiac-scorpio",
    "zodiac-taurus", "zodiac-virgo", "zoom-in", "zoom-out",
})


def validate_icon(icon: str) -> Optional[str]:
    """Return the icon name if valid for Mintlify, or None if not.

    Checks against FontAwesome 6.x (free + pro) and Lucide icon sets.
    Returns None for platform-specific icons (e.g. custom GitBook icons)
    that would render as missing in Mintlify.
    """
    if not icon:
        return None
    icon = icon.strip().lower()
    if icon in VALID_ICONS:
        return icon
    return None
